import Foundation

// Render variants: several rendering methodologies in ONE build, switchable
// at runtime, measurable against each other, and — the part that matters —
// impossible to lose the meaning of.
//
// THE PROBLEM THIS EXISTS TO SOLVE
//
// The obvious way to try a rendering idea is to change the renderer. Do that
// twice and the first idea is gone: the code says what it does NOW, and
// nothing anywhere says what the previous approach was worth or why it was
// abandoned. A git branch does not fix it either — two branches cannot be
// A/B-ed in one run, and the measurements still live nowhere.
//
// THE THREE RULES, and none of them is the switch
//
//   1. A variant is a FROZEN POINT. `RenderAxes` is composable — decode path
//      × curves × tone response × white balance — but a variant is one named,
//      fixed combination of them.
//
//   2. THE REGISTRY IS APPEND-ONLY. Once a variant has been measured and its
//      numbers are in the ledger, its axes are never edited. Improving `D1`
//      means ADDING `D1.5`. This is the whole mechanism: a variant id in the
//      ledger always means exactly one thing, forever.
//
//   3. RESULTS LIVE IN GIT beside the definitions —
//      `docs/render-variants/ledger.md`, regenerated by
//      `tools/render_bench.py`. A gain that is not written down did not
//      happen.
//
// Selection follows `RawDecodePath`'s idiom exactly, because it is the same
// problem and the app already teaches it: `current` over `UserDefaults`, a
// Settings picker, `--variant` on the CLI, `LL_VARIANT` for a staged run.

/// One axis of the rendering space. Composable, so a new idea is a new field
/// here rather than a new hand-written pipeline; but what gets tested and
/// recorded is always a named `RenderVariant` that fixes every axis.
public struct RenderAxes: Equatable, Sendable, Codable {

    /// Which raw decode pipeline converts the file to linear light.
    public var decodePath: RawDecodePath

    /// Which of a sidecar's tone curves the render honours.
    ///
    /// A Lightroom file carries two, and they are different things: the
    /// IMAGE's own curve is the photographer's, and the LOOK's belongs to the
    /// named profile ("Adobe Color", "Adobe Landscape") and applies whether
    /// or not the photographer touched a curve.
    public enum ToneCurveHandling: String, Equatable, Sendable, Codable {
        /// Neither — the engine's own tone response, unmodified. What every
        /// build before variants existed did.
        case ignore
        /// The image's own curve only.
        case image
        /// The image's curve and the profile look's, in that order.
        case imageAndLook
    }
    public var toneCurves: ToneCurveHandling

    /// How strongly the tone sliders respond, relative to what the sidecar
    /// literally says.
    ///
    /// A calibration, not a correction of the file: Lightroom's Highlights
    /// −78 and ours are the same NUMBER through two different curves, and the
    /// scale that makes them agree is an empirical question these variants
    /// exist to answer.
    public var highlightsScale: Double
    public var shadowsScale: Double

    /// A flat exposure trim in EV, added to whatever the sidecar asks for.
    ///
    /// Not a fudge: the first corpus run showed every variant landing
    /// consistently BRIGHT against Lightroom — +0.27 to +0.87 stops, on all
    /// five files and all five variants. A systematic offset that survives
    /// every other axis is a property of the two renderers' baselines, and
    /// this is the axis that lets it be measured rather than argued about.
    public var exposureOffset: Double

    /// Whether a sidecar's own white balance is honoured or left as shot.
    public var honoursWhiteBalance: Bool

    public init(
        decodePath: RawDecodePath = .bradfordAdaptation,
        toneCurves: ToneCurveHandling = .ignore,
        highlightsScale: Double = 1,
        shadowsScale: Double = 1,
        exposureOffset: Double = 0,
        honoursWhiteBalance: Bool = true
    ) {
        self.decodePath = decodePath
        self.toneCurves = toneCurves
        self.highlightsScale = highlightsScale
        self.shadowsScale = shadowsScale
        self.exposureOffset = exposureOffset
        self.honoursWhiteBalance = honoursWhiteBalance
    }

    /// A one-line spelling of every axis, for the ledger. Stable and
    /// exhaustive on purpose: a row in the ledger has to be readable years
    /// later without the code beside it.
    public var summary: String {
        var parts = ["decode=\(decodePath.rawValue)", "curves=\(toneCurves.rawValue)"]
        if highlightsScale != 1 { parts.append(String(format: "highlights×%.2f", highlightsScale)) }
        if shadowsScale != 1 { parts.append(String(format: "shadows×%.2f", shadowsScale)) }
        if exposureOffset != 0 { parts.append(String(format: "exposure%+.2fEV", exposureOffset)) }
        if !honoursWhiteBalance { parts.append("wb=asShot") }
        return parts.joined(separator: " ")
    }
}

/// One named, frozen rendering methodology.
public struct RenderVariant: Identifiable, Equatable, Sendable {

    /// The id that appears in the ledger, on the CLI and in Settings — "A",
    /// "B", "D1.5". **Never reused, never redefined.**
    public let id: String
    /// What this variant is, in one line.
    public let title: String
    /// What it is TESTING — the question it was added to answer. The single
    /// most valuable field here: a result without its hypothesis is a number
    /// nobody can act on.
    public let hypothesis: String
    public let axes: RenderAxes

    public init(id: String, title: String, hypothesis: String, axes: RenderAxes) {
        self.id = id
        self.title = title
        self.hypothesis = hypothesis
        self.axes = axes
    }
}

/// Every render variant that has ever been defined.
///
/// **APPEND ONLY.** Adding is free. Editing an existing variant's axes
/// silently invalidates every ledger row that names it, which is exactly the
/// loss of understanding this whole file exists to prevent. If a variant
/// needs to change, add the next one — `D1` becomes `D1.5`, not a new `D1`.
///
/// `RenderVariantTests` enforces what it can: unique ids, a hypothesis on
/// every entry, and that `.baseline` is present and neutral.
public enum RenderVariantRegistry {

    /// The variant a build uses when nobody has chosen: today's renderer,
    /// unchanged. Its numbers are the line every other variant is judged
    /// against, so it must stay a true no-op.
    public static let baselineID = "A"

    public static let all: [RenderVariant] = [
        RenderVariant(
            id: "A",
            title: "Baseline — the shipping renderer",
            hypothesis: """
                The control. Bradford adaptation, no curve of any kind, sliders \
                honoured exactly as the sidecar writes them. Every other \
                variant is measured as a delta from this one.
                """,
            axes: RenderAxes()),

        RenderVariant(
            id: "B",
            title: "Honour the profile's look curve",
            hypothesis: """
                A Lightroom file renders through its named profile, and that \
                profile carries a tone curve the photographer never sees — \
                Adobe Color's lifts 224→230 and pulls 22→16. Measured at \
                −0.24 ΔE on _WEX3825 before variants existed, which is real \
                but small; this variant is what re-measures it across a \
                corpus rather than one file.
                """,
            axes: RenderAxes(toneCurves: .imageAndLook)),

        RenderVariant(
            id: "C",
            title: "Adobe's own camera profile",
            hypothesis: """
                Decode through the DCP Lightroom itself names, rather than \
                Apple's camera profile. Measured WORSE on one file (+0.14 ΔE), \
                which was surprising enough to be worth a corpus. Needs \
                Adobe's profile set installed, so it is unavailable on iOS and \
                on a Mac without Lightroom.
                """,
            axes: RenderAxes(decodePath: .dcpProfile)),

        RenderVariant(
            id: "D",
            title: "Calibrated tone response",
            hypothesis: """
                Our Highlights and Shadows are the same numbers through a \
                different curve, and the full-strength import over-flattens: \
                shadows come out +0.08 too bright and highlights −0.12 too \
                dark. A one-file fit put shadows at ×0.7 and left highlights \
                alone. This is that fit, frozen, to see whether it generalises.
                """,
            axes: RenderAxes(shadowsScale: 0.7)),

        RenderVariant(
            id: "D1",
            title: "Calibrated tone response, plus the look curve",
            hypothesis: """
                B and D together. Each was worth something alone and they act \
                on different parts of the range, so the question is whether \
                they add or interfere.
                """,
            axes: RenderAxes(toneCurves: .imageAndLook, shadowsScale: 0.7)),

        RenderVariant(
            id: "E",
            title: "D1, plus the systematic exposure offset nulled",
            hypothesis: """
                The first corpus run (2026-09-07, batch1) found every variant                 landing BRIGHT against Lightroom by +0.27 to +0.87 stops — on                 all five files and all five variants, so it is a property of                 the two baselines rather than of any slider. D1's mean offset                 was +0.47 EV. This is D1 with that nulled, to find out whether                 the brightness IS the error or merely correlates with it.
                """,
            axes: RenderAxes(
                toneCurves: .imageAndLook, shadowsScale: 0.7, exposureOffset: -0.47)),
    ]

    public static func variant(id: String) -> RenderVariant? {
        all.first { $0.id.caseInsensitiveCompare(id) == .orderedSame }
    }

    public static var baseline: RenderVariant {
        variant(id: baselineID) ?? RenderVariant(
            id: baselineID, title: "Baseline", hypothesis: "", axes: RenderAxes())
    }

    /// Whether this build and machine can actually run a variant — the decode
    /// path is the only axis that can be unavailable, and it already knows.
    public static func isAvailable(_ variant: RenderVariant) -> Bool {
        RawDecodePathRegistry.isAvailable(variant.axes.decodePath)
    }

    public static var available: [RenderVariant] { all.filter(isAvailable) }

    // MARK: - Selection

    /// `UserDefaults` key backing `current`.
    public static let defaultsKey = "renderVariant"

    /// The process-wide selection, shared by the app's Settings picker, the
    /// CLI's `--variant` and the tests — one switch, exactly as
    /// `RawDecodePath.current` does it.
    ///
    /// An unknown or unavailable stored id resolves back to the baseline
    /// rather than failing at render time: a variant removed from a build,
    /// or a DCP variant on a machine without Adobe's profiles, must not
    /// leave somebody with an editor that cannot draw.
    public static var current: RenderVariant {
        get {
            guard let id = UserDefaults.standard.string(forKey: defaultsKey),
                  let variant = variant(id: id), isAvailable(variant) else {
                return baseline
            }
            return variant
        }
        set { UserDefaults.standard.set(newValue.id, forKey: defaultsKey) }
    }
}
