import CoreImage
import simd
import XCTest
@testable import LetsLapseKit

/// The `.cube` parser's promises and the LUT stage's: Windows-ended files
/// parse, the title is metadata not identity, an identity cube is the
/// identity through Core Image, strength is a straight mix, and the log-input
/// heuristic tells a display LUT from a log one.
final class CubeLUTTests: XCTestCase {

    private let context = CIContext(options: [
        .useSoftwareRenderer: false,
        .workingColorSpace: CGColorSpace(name: CGColorSpace.linearSRGB)!,
    ])

    private func patch(_ r: CGFloat, _ g: CGFloat, _ b: CGFloat) -> CIImage {
        CIImage(color: CIColor(red: r, green: g, blue: b, colorSpace: CGColorSpace(name: CGColorSpace.sRGB)!)!)
            .cropped(to: CGRect(x: 0, y: 0, width: 8, height: 8))
    }

    /// The centre pixel in sRGB-encoded 0…1.
    private func read(_ image: CIImage) -> SIMD3<Double> {
        var pixel = [Float](repeating: 0, count: 4)
        context.render(image, toBitmap: &pixel, rowBytes: 16,
                       bounds: CGRect(x: 4, y: 4, width: 1, height: 1),
                       format: .RGBAf, colorSpace: CGColorSpace(name: CGColorSpace.sRGB))
        return SIMD3(Double(pixel[0]), Double(pixel[1]), Double(pixel[2]))
    }

    /// A 2-point cube as text, with the line ending asked for.
    private func cubeText(newline: String, title: String = "\"Test\"", extra: String = "") -> String {
        let rows = ["0 0 0", "1 0 0", "0 1 0", "1 1 0", "0 0 1", "1 0 1", "0 1 1", "1 1 1"]
        return (["# comment", "TITLE \(title)", extra, "LUT_3D_SIZE 2", ""] + rows)
            .filter { !$0.isEmpty || true }.joined(separator: newline) + newline
    }

    // MARK: Parsing

    func testParsesUnixAndWindowsLineEndings() throws {
        let lf = try CubeLUT.parse(Data(cubeText(newline: "\n").utf8))
        let crlf = try CubeLUT.parse(Data(cubeText(newline: "\r\n").utf8))
        XCTAssertEqual(lf.size, 2)
        XCTAssertEqual(crlf.size, 2)
        XCTAssertEqual(lf.rgba, crlf.rgba)
        XCTAssertEqual(lf.title, "Test")
        // Different bytes, different identity — the hash is of the file.
        XCTAssertNotEqual(lf.contentHash, crlf.contentHash)
        XCTAssertEqual(lf.contentHash.count, 64)
    }

    func testReadsDomainAndUnquotedTitle() throws {
        let cube = try CubeLUT.parse(Data(cubeText(
            newline: "\n", title: "lutCreatorJs_25", extra: "DOMAIN_MIN 0 0 0\nDOMAIN_MAX 2 2 2").utf8))
        XCTAssertEqual(cube.title, "lutCreatorJs_25")
        XCTAssertEqual(cube.maker, "lutCreatorJs")
        XCTAssertEqual(cube.domainMax, SIMD3(2, 2, 2))
        // Sampling honours the domain: the file's white sits at input 2.
        let atTwo = cube.sample(SIMD3(2, 2, 2))
        XCTAssertEqual(atTwo.x, 1, accuracy: 1e-5)
    }

    func testRefusesWhatItCannotRender() {
        XCTAssertThrowsError(try CubeLUT.parse(Data("TITLE x\nLUT_1D_SIZE 4\n0 0 0\n".utf8))) {
            XCTAssertEqual($0 as? CubeLUT.ParseError, .oneDimensional)
        }
        XCTAssertThrowsError(try CubeLUT.parse(Data("0 0 0\n1 1 1\n".utf8))) {
            XCTAssertEqual($0 as? CubeLUT.ParseError, .noSize)
        }
        XCTAssertThrowsError(try CubeLUT.parse(Data("LUT_3D_SIZE 2\n0 0 0\n1 1 1\n".utf8))) {
            XCTAssertEqual($0 as? CubeLUT.ParseError, .entryCount(expected: 8, found: 2))
        }
        XCTAssertThrowsError(try CubeLUT.parse(Data("LUT_3D_SIZE 200\n".utf8))) {
            XCTAssertEqual($0 as? CubeLUT.ParseError, .sizeOutOfRange(200))
        }
    }

    func testTitleIsMetadataNotIdentity() {
        let cube = CubeLUT.make(size: 3, title: "Generated by Resolve") { $0 }
        XCTAssertEqual(cube.maker, "Resolve")
        XCTAssertNil(CubeLUT.make(size: 3, title: "") { $0 }.maker)
        XCTAssertEqual(cube.sizeDescription, "3 × 3 × 3")
    }

    func testFileTextRoundTrips() throws {
        let built = CubeLUT.make(size: 5, title: "Round trip") { SIMD3($0.z, $0.y, $0.x) }
        let parsed = try CubeLUT.parse(Data(built.cubeFileText().utf8))
        XCTAssertEqual(parsed.size, 5)
        XCTAssertEqual(parsed.title, "Round trip")
        for (a, b) in zip(built.rgba, parsed.rgba) { XCTAssertEqual(a, b, accuracy: 1e-5) }
    }

    // MARK: Rendering

    func testIdentityCubeIsTheIdentity() {
        let cube = CubeLUT.identity(size: 17)
        let before = patch(0.62, 0.31, 0.12)
        let after = cube.apply(to: before)
        let a = read(before), b = read(after)
        XCTAssertEqual(a.x, b.x, accuracy: 2.0 / 255)
        XCTAssertEqual(a.y, b.y, accuracy: 2.0 / 255)
        XCTAssertEqual(a.z, b.z, accuracy: 2.0 / 255)
    }

    func testCubeSwapsChannelsAndStrengthMixes() {
        let swap = CubeLUT.make(size: 9, title: "swap") { SIMD3($0.z, $0.y, $0.x) }
        let before = patch(0.8, 0.4, 0.2)
        let full = read(swap.apply(to: before))
        XCTAssertEqual(full.x, 0.2, accuracy: 2.0 / 255)
        XCTAssertEqual(full.z, 0.8, accuracy: 2.0 / 255)
        let half = read(swap.apply(to: before, strength: 0.5))
        XCTAssertEqual(half.x, 0.5, accuracy: 3.0 / 255)
        XCTAssertEqual(half.z, 0.5, accuracy: 3.0 / 255)
        // Strength 0 is the input, untouched — the same object.
        XCTAssertTrue(swap.apply(to: before, strength: 0) === before)
    }

    func testLogInputHeuristic() {
        XCTAssertFalse(CubeLUT.identity(size: 9).isLikelyLogInput)
        // A Log→709 cube: mid grey expected near 0.4, so 0.5 in maps low and
        // 0.18 in maps near black.
        let log = CubeLUT.make(size: 9, title: "log") { v in
            let out = simd_clamp((v - 0.35) * 0.6, SIMD3(repeating: 0), SIMD3(repeating: 1))
            return out
        }
        XCTAssertTrue(log.isLikelyLogInput)
    }

    // MARK: The stage

    func testRecipeCarriesTheLayerIntoThePostPasses() {
        let swap = CubeLUT.make(size: 9, title: "swap") { SIMD3($0.z, $0.y, $0.x) }
        LUTRegistry.shared.register(swap)
        var recipe = GradeRecipe()
        XCTAssertFalse(EnginePostPasses.isNeeded(recipe))
        recipe.lut = LUTLayer(id: swap.contentHash, strength: 1)
        XCTAssertTrue(recipe.hasLUT)
        XCTAssertTrue(EnginePostPasses.isNeeded(recipe))
        XCTAssertNotEqual(recipe.cacheToken, GradeRecipe().cacheToken)
        XCTAssertTrue(recipe.cacheToken.contains("|lut"))
        let before = patch(0.8, 0.4, 0.2)
        let after = read(EnginePostPasses.apply(before, recipe: recipe))
        XCTAssertEqual(after.x, 0.2, accuracy: 2.0 / 255)
        // A layer at zero strength is not a pass.
        recipe.lut = LUTLayer(id: swap.contentHash, strength: 0)
        XCTAssertFalse(EnginePostPasses.isNeeded(recipe))
        // An unknown id renders as no LUT rather than as nothing.
        recipe.lut = LUTLayer(id: "nope", strength: 1)
        let untouched = read(EnginePostPasses.apply(before, recipe: recipe))
        XCTAssertEqual(untouched.x, 0.8, accuracy: 2.0 / 255)
    }

    func testRegistryResolvesOnDemand() {
        let registry = LUTRegistry()
        let cube = CubeLUT.identity(size: 3)
        var asked: [String] = []
        registry.setResolver { id in asked.append(id); return id == cube.contentHash ? cube : nil }
        XCTAssertNil(registry.cube(for: "missing"))
        XCTAssertEqual(registry.cube(for: cube.contentHash)?.size, 3)
        // Kept after the first resolve.
        XCTAssertEqual(registry.cube(for: cube.contentHash)?.size, 3)
        XCTAssertEqual(asked, ["missing", cube.contentHash])
    }

    func testRegistryRemembersMissesUntilTold() {
        let registry = LUTRegistry()
        let cube = CubeLUT.identity(size: 3)
        var asked = 0
        registry.setResolver { _ in asked += 1; return nil }
        XCTAssertNil(registry.cube(for: cube.contentHash))
        XCTAssertNil(registry.cube(for: cube.contentHash))
        XCTAssertEqual(asked, 1, "a miss is asked once, not on every frame")
        // A registration answers a remembered miss without the resolver.
        registry.register(cube)
        XCTAssertEqual(registry.cube(for: cube.contentHash)?.size, 3)
        XCTAssertEqual(asked, 1)
        // Forgetting the misses asks again — a store import, a fold, a switch.
        XCTAssertNil(registry.cube(for: "other"))
        registry.forgetMisses()
        XCTAssertNil(registry.cube(for: "other"))
        XCTAssertEqual(asked, 3)
        // A new resolver starts clean too.
        registry.setResolver { _ in asked += 1; return nil }
        XCTAssertNil(registry.cube(for: "other"))
        XCTAssertEqual(asked, 4)
    }

    func testDisplayGradeAppliesTheLUTToo() {
        let swap = CubeLUT.make(size: 9, title: "swap") { SIMD3($0.z, $0.y, $0.x) }
        LUTRegistry.shared.register(swap)
        var grade = DisplayGrade()
        grade.lut = LUTLayer(id: swap.contentHash)
        XCTAssertFalse(grade.isNeutral)
        let after = read(DisplayGrade.apply(patch(0.8, 0.4, 0.2), grade, asShotKelvin: 6500))
        XCTAssertEqual(after.x, 0.2, accuracy: 2.0 / 255)
    }
}
