import CoreImage
import CryptoKit
import Foundation

// A 3D colour lookup table from a `.cube` file, and the one stage that
// renders it.
//
// A LUT is a look somebody else made — Lightroom, Resolve, a LUT pack — and
// the app treats it as the LAST colour operation: after the tone engine,
// after dehaze and the HSL panel (`EnginePostPasses`), on the display-
// referred picture, looked up in sRGB because that is the cube every
// display LUT is defined on. The parametric sliders therefore sit on the
// LUT's INPUT, which is Lightroom's profile-then-sliders order and the only
// order the Metal engine allows without moving the cube into its kernel.
//
// Verified 2026-09-08 on Steven's eight files (docs/presets-lut-spike.md):
// `CIColorCubeWithColorSpace` takes the `.cube` data in its own order (red
// varying fastest, RGBA float32), accepts 2…128 a side, and round-trips an
// identity cube within 1/255. Two traps live in the parser and are pinned by
// tests: Swift's `Character` treats CRLF as ONE grapheme, so a split on "\n"
// finds nothing in a Windows-ended file; and `TITLE` is not a name — five
// of the eight say "Generated by Resolve".

/// A LUT as a grade carries it: which cube, and how much of it.
///
/// The cube itself is NOT here — a recipe is compared, encoded and cached
/// per frame, and a 33³ cube is 431 KB of floats. The id is the cube's
/// content hash; `LUTRegistry` turns it back into pixels.
public struct LUTLayer: Codable, Equatable, Hashable, Sendable {
    /// The cube's content hash (`CubeLUT.contentHash`).
    public var id: String
    /// 0…1: how far from the input toward the cube's output. 1 is the LUT as
    /// its author made it.
    public var strength: Float

    public init(id: String, strength: Float = 1) {
        self.id = id
        self.strength = min(max(strength, 0), 1)
    }

    /// True when the layer would change a pixel.
    public var isActive: Bool { strength > 0.0005 }

    public var cacheToken: String {
        String(id.prefix(12)) + String(format: "@%.3f", strength)
    }
}

/// One parsed `.cube` file.
public struct CubeLUT: Sendable {
    /// The file's `TITLE`, or "" — see `maker` before showing it.
    public var title: String
    /// Entries per axis. 33 and 25 in the wild; 17, 64 and 65 also seen.
    public var size: Int
    /// The input range the cube is defined over. 0…1 unless the file says
    /// otherwise, which it almost never does.
    public var domainMin: SIMD3<Float>
    public var domainMax: SIMD3<Float>
    /// `size³ × 4` floats, red varying fastest, alpha 1 — the layout
    /// `CIColorCubeWithColorSpace` reads directly.
    public var rgba: [Float]
    /// SHA-256 of the bytes this was parsed from (or, for a built cube, of
    /// its float data). The identity a grade stores and a store files under.
    public var contentHash: String
    /// The smallest and largest output values in the file. A few cubes stray
    /// outside 0…1 (CAPEA: −0.053…1.007); they are passed through as floats
    /// and clip at the 8-bit readback.
    public var minValue: Float
    public var maxValue: Float

    /// `CIColorCubeWithColorSpace`'s own limit on `inputCubeDimension`.
    public static let sizeRange = 2...128

    public enum ParseError: Error, LocalizedError, Equatable {
        case oneDimensional
        case noSize
        case sizeOutOfRange(Int)
        case entryCount(expected: Int, found: Int)

        public var errorDescription: String? {
            switch self {
            case .oneDimensional:
                return "This is a 1D LUT (LUT_1D_SIZE); only 3D cubes are supported."
            case .noSize:
                return "No LUT_3D_SIZE line — this doesn't look like a .cube file."
            case .sizeOutOfRange(let n):
                return "A \(n)-point cube is outside the \(sizeRange.lowerBound)…\(sizeRange.upperBound) Core Image can load."
            case .entryCount(let expected, let found):
                return "Expected \(expected) colour entries for this cube size, found \(found)."
            }
        }
    }

    public init(
        title: String, size: Int, domainMin: SIMD3<Float> = .zero, domainMax: SIMD3<Float> = .one,
        rgba: [Float], contentHash: String, minValue: Float, maxValue: Float
    ) {
        self.title = title
        self.size = size
        self.domainMin = domainMin
        self.domainMax = domainMax
        self.rgba = rgba
        self.contentHash = contentHash
        self.minValue = minValue
        self.maxValue = maxValue
    }

    // MARK: - Parsing

    public static func parse(contentsOf url: URL) throws -> CubeLUT {
        try parse(try Data(contentsOf: url))
    }

    /// Reads a `.cube`: comments, `TITLE`, `LUT_3D_SIZE`, `DOMAIN_MIN/MAX`,
    /// then `size³` rows of three floats. Latin-1 is accepted where the file
    /// is not UTF-8 (a `©` in a comment is enough to make it not).
    public static func parse(_ data: Data) throws -> CubeLUT {
        let text = String(data: data, encoding: .utf8) ?? String(decoding: data, as: UTF8.self)
        var title = ""
        var size = 0
        var domainMin = SIMD3<Float>(repeating: 0)
        var domainMax = SIMD3<Float>(repeating: 1)
        var rgba: [Float] = []
        var low = Float.greatestFiniteMagnitude
        var high = -Float.greatestFiniteMagnitude
        // `isNewline` is true for the "\r\n" grapheme; "== \n" is not.
        for raw in text.split(omittingEmptySubsequences: true, whereSeparator: { $0.isNewline }) {
            let line = raw.trimmingCharacters(in: .whitespaces)
            guard let first = line.first, first != "#" else { continue }
            if first.isLetter {
                let parts = line.split(separator: " ", maxSplits: 1, omittingEmptySubsequences: true)
                let key = parts[0].uppercased()
                let rest = parts.count > 1 ? parts[1].trimmingCharacters(in: .whitespaces) : ""
                switch key {
                case "TITLE":
                    title = rest.trimmingCharacters(in: CharacterSet(charactersIn: "\""))
                case "LUT_3D_SIZE":
                    size = Int(rest) ?? 0
                    if rgba.isEmpty, sizeRange.contains(size) {
                        rgba.reserveCapacity(size * size * size * 4)
                    }
                case "LUT_1D_SIZE":
                    throw ParseError.oneDimensional
                case "DOMAIN_MIN":
                    let v = rest.split(separator: " ").compactMap { Float($0) }
                    if v.count == 3 { domainMin = SIMD3(v[0], v[1], v[2]) }
                case "DOMAIN_MAX":
                    let v = rest.split(separator: " ").compactMap { Float($0) }
                    if v.count == 3 { domainMax = SIMD3(v[0], v[1], v[2]) }
                default:
                    continue
                }
                continue
            }
            var values: [Float] = []
            values.reserveCapacity(3)
            for token in line.split(whereSeparator: { $0 == " " || $0 == "\t" }) {
                guard let value = Float(token) else { values.removeAll(); break }
                values.append(value)
            }
            guard values.count == 3 else { continue }
            low = min(low, values[0], values[1], values[2])
            high = max(high, values[0], values[1], values[2])
            rgba.append(values[0]); rgba.append(values[1]); rgba.append(values[2]); rgba.append(1)
        }
        guard size > 0 else { throw ParseError.noSize }
        guard sizeRange.contains(size) else { throw ParseError.sizeOutOfRange(size) }
        let expected = size * size * size
        guard rgba.count == expected * 4 else {
            throw ParseError.entryCount(expected: expected, found: rgba.count / 4)
        }
        return CubeLUT(
            title: title, size: size, domainMin: domainMin, domainMax: domainMax,
            rgba: rgba, contentHash: Self.hash(of: data), minValue: low, maxValue: high)
    }

    static func hash(of data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Building

    /// A cube made from a function of linear-in-cube RGB — the identity, a
    /// test fixture, a demo tint for a screenshot.
    public static func make(
        size: Int, title: String, _ transform: (SIMD3<Float>) -> SIMD3<Float>
    ) -> CubeLUT {
        precondition(sizeRange.contains(size))
        var rgba: [Float] = []
        rgba.reserveCapacity(size * size * size * 4)
        var low = Float.greatestFiniteMagnitude, high = -Float.greatestFiniteMagnitude
        let step = 1 / Float(size - 1)
        for b in 0..<size {
            for g in 0..<size {
                for r in 0..<size {
                    let out = transform(SIMD3(Float(r) * step, Float(g) * step, Float(b) * step))
                    low = min(low, out.x, out.y, out.z)
                    high = max(high, out.x, out.y, out.z)
                    rgba.append(out.x); rgba.append(out.y); rgba.append(out.z); rgba.append(1)
                }
            }
        }
        let bytes = rgba.withUnsafeBufferPointer { Data(buffer: $0) }
        return CubeLUT(
            title: title, size: size, rgba: rgba, contentHash: hash(of: bytes),
            minValue: low, maxValue: high)
    }

    public static func identity(size: Int = 17) -> CubeLUT {
        make(size: size, title: "Identity") { $0 }
    }

    /// This cube written back out as `.cube` text — how a built cube becomes
    /// a file a store can keep beside the imported ones.
    public func cubeFileText() -> String {
        var out = "TITLE \"\(title)\"\nLUT_3D_SIZE \(size)\n"
        if domainMin != .zero || domainMax != .one {
            out += "DOMAIN_MIN \(domainMin.x) \(domainMin.y) \(domainMin.z)\n"
            out += "DOMAIN_MAX \(domainMax.x) \(domainMax.y) \(domainMax.z)\n"
        }
        out.reserveCapacity(size * size * size * 30)
        var i = 0
        while i < rgba.count {
            out += String(format: "%.6f %.6f %.6f\n", rgba[i], rgba[i + 1], rgba[i + 2])
            i += 4
        }
        return out
    }

    // MARK: - Reading the cube

    /// Trilinear sample at an input colour, the domain applied. The renderer
    /// never comes through here — it is for probes and tests.
    public func sample(_ input: SIMD3<Float>) -> SIMD3<Float> {
        let n = size
        let span = domainMax - domainMin
        func axis(_ v: Float, _ lo: Float, _ range: Float) -> (Int, Float) {
            let unit = range > 0 ? (v - lo) / range : v
            let s = min(max(unit, 0), 1) * Float(n - 1)
            let i = min(Int(s), n - 2)
            return (i, s - Float(i))
        }
        let (ri, rf) = axis(input.x, domainMin.x, span.x)
        let (gi, gf) = axis(input.y, domainMin.y, span.y)
        let (bi, bf) = axis(input.z, domainMin.z, span.z)
        func at(_ dr: Int, _ dg: Int, _ db: Int) -> SIMD3<Float> {
            let index = (((bi + db) * n + (gi + dg)) * n + (ri + dr)) * 4
            return SIMD3(rgba[index], rgba[index + 1], rgba[index + 2])
        }
        let c00 = at(0, 0, 0) * (1 - rf) + at(1, 0, 0) * rf
        let c10 = at(0, 1, 0) * (1 - rf) + at(1, 1, 0) * rf
        let c01 = at(0, 0, 1) * (1 - rf) + at(1, 0, 1) * rf
        let c11 = at(0, 1, 1) * (1 - rf) + at(1, 1, 1) * rf
        let c0 = c00 * (1 - gf) + c10 * gf
        let c1 = c01 * (1 - gf) + c11 * gf
        return c0 * (1 - bf) + c1 * bf
    }

    /// Rec.709 luma of what the cube makes of a neutral grey.
    public func luma(ofGrey grey: Float) -> Float {
        let out = sample(SIMD3(repeating: grey))
        return 0.2126 * out.x + 0.7152 * out.y + 0.0722 * out.z
    }

    /// True when the cube expects a log-encoded picture: a Log→709 cube sends
    /// mid grey toward black because the log curve it expects put it near
    /// 0.4. On a display-referred photo such a cube looks crushed. The
    /// threshold sits under the darkest of the eight display LUTs measured
    /// (LUT-G2 maps 50 % to ~0.36).
    public var isLikelyLogInput: Bool { luma(ofGrey: 0.5) < 0.25 }

    /// Who made it, from the title — or nil when the title says nothing a
    /// person would recognise. Never the name: name a LUT after its file.
    public var maker: String? {
        let lower = title.lowercased()
        if lower.contains("resolve") { return "Resolve" }
        if lower.contains("vegas") { return "VEGAS Pro" }
        if lower.contains("lutcreator") { return "lutCreatorJs" }
        if lower.contains("iwltbap") { return "IWLTBAP" }
        let trimmed = title.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }

    /// "33 × 33 × 33".
    public var sizeDescription: String { "\(size) × \(size) × \(size)" }

    // MARK: - Rendering

    /// The lookup space. A display LUT is defined on the sRGB/Rec.709 cube
    /// whatever the working space; the filter converts in and out.
    public static let lookupSpace = CGColorSpace(name: CGColorSpace.sRGB)!

    /// `image` through the cube at `strength`. Strength is baked into the
    /// cube itself — each entry mixed toward the identity lattice by
    /// `1 − strength` — rather than blended afterwards: the lattice is in the
    /// LUT's own encoded space, so 50 % reads as halfway to the eye, where a
    /// Core Image blend would mix in linear light and read as 60 %. Neutral
    /// at strength 0 hands the input back untouched.
    public func apply(to image: CIImage, strength: Float = 1) -> CIImage {
        let amount = min(max(strength, 0), 1)
        guard amount > 0.0005 else { return image }
        var input = image
        if domainMin != .zero || domainMax != .one {
            // The cube is defined over a non-unit input range: map it onto
            // 0…1 so the filter's own 0…1 lookup lands where the file says.
            let span = domainMax - domainMin
            let scale = SIMD3<Float>(
                span.x > 0 ? 1 / span.x : 1, span.y > 0 ? 1 / span.y : 1, span.z > 0 ? 1 / span.z : 1)
            input = input.applyingFilter("CIColorMatrix", parameters: [
                "inputRVector": CIVector(x: CGFloat(scale.x), y: 0, z: 0, w: 0),
                "inputGVector": CIVector(x: 0, y: CGFloat(scale.y), z: 0, w: 0),
                "inputBVector": CIVector(x: 0, y: 0, z: CGFloat(scale.z), w: 0),
                "inputBiasVector": CIVector(
                    x: CGFloat(-domainMin.x * scale.x), y: CGFloat(-domainMin.y * scale.y),
                    z: CGFloat(-domainMin.z * scale.z), w: 0),
            ])
        }
        guard let cube = CIFilter(name: "CIColorCubeWithColorSpace") else { return image }
        cube.setValue(input, forKey: kCIInputImageKey)
        cube.setValue(size, forKey: "inputCubeDimension")
        cube.setValue(cubeData(strength: amount), forKey: "inputCubeData")
        cube.setValue(Self.lookupSpace, forKey: "inputColorSpace")
        return cube.outputImage ?? image
    }

    /// The float data the filter reads: the cube as it is at full strength,
    /// else every entry mixed toward the identity lattice. A 33³ cube is
    /// 144 k floats — under a millisecond, so a slider can drive it live.
    func cubeData(strength: Float) -> Data {
        guard strength < 0.9995 else {
            return rgba.withUnsafeBufferPointer { Data(buffer: $0) }
        }
        var mixed = rgba
        let step = 1 / Float(size - 1)
        let keep = 1 - strength
        var i = 0
        for b in 0..<size {
            let lb = Float(b) * step * keep
            for g in 0..<size {
                let lg = Float(g) * step * keep
                for r in 0..<size {
                    mixed[i] = mixed[i] * strength + Float(r) * step * keep
                    mixed[i + 1] = mixed[i + 1] * strength + lg
                    mixed[i + 2] = mixed[i + 2] * strength + lb
                    i += 4
                }
            }
        }
        return mixed.withUnsafeBufferPointer { Data(buffer: $0) }
    }
}

/// Turns a `LUTLayer.id` back into a cube for the render paths.
///
/// The Kit renders recipes; it does not know where the app keeps its LUT
/// files. The app installs a `resolver` that reads one on demand; the CLI
/// registers the cube it was handed on the command line. Thread-safe: the
/// post passes run on render queues.
public final class LUTRegistry: @unchecked Sendable {
    public static let shared = LUTRegistry()

    private let lock = NSLock()
    private var cubes: [String: CubeLUT] = [:]
    private var resolver: (@Sendable (String) -> CubeLUT?)?

    public init() {}

    /// Installs the lookup used for an id nobody has registered. Replaces
    /// any earlier one.
    public func setResolver(_ resolver: (@Sendable (String) -> CubeLUT?)?) {
        lock.lock(); defer { lock.unlock() }
        self.resolver = resolver
    }

    public func register(_ cube: CubeLUT) {
        lock.lock(); defer { lock.unlock() }
        cubes[cube.contentHash] = cube
    }

    public func forget(_ id: String) {
        lock.lock(); defer { lock.unlock() }
        cubes.removeValue(forKey: id)
    }

    /// The cube for an id: registered, else resolved and kept.
    public func cube(for id: String) -> CubeLUT? {
        lock.lock()
        if let cube = cubes[id] { lock.unlock(); return cube }
        let resolve = resolver
        lock.unlock()
        guard let cube = resolve?(id) else { return nil }
        lock.lock(); cubes[id] = cube; lock.unlock()
        return cube
    }
}
