import Foundation
import LetsLapseKit

/// One imported cube, as the store lists it. The pixels live in the file
/// (`luts/<hash>.cube`) and, once read, in `LUTRegistry`; this is what the
/// Presets sheet shows about it.
struct LUTFile: Identifiable, Codable, Equatable {
    /// The cube's content hash — `LUTLayer.id`, and the file's name.
    var id: String
    /// The file name it was imported under, extension included.
    var fileName: String
    /// The file's own `TITLE`, kept as a note ("Generated by Resolve").
    var title: String
    /// Entries per axis.
    var size: Int
    var byteCount: Int
    var importedAt: Date
    /// True when the cube expects a log-encoded picture (`CubeLUT.isLikelyLogInput`).
    var isLikelyLogInput: Bool

    var sizeDescription: String { "\(size) × \(size) × \(size)" }

    /// Who made it, from the title — nil when the title names nobody.
    var maker: String? {
        let lower = title.lowercased()
        if lower.contains("resolve") { return "Resolve" }
        if lower.contains("vegas") { return "VEGAS Pro" }
        if lower.contains("lutcreator") { return "lutCreatorJs" }
        if lower.contains("iwltbap") { return "IWLTBAP" }
        let trimmed = title.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }

    /// "Teal_and_Orange.cube" → "Teal and Orange": the name a preset starts
    /// with. Never the TITLE — five of Steven's eight say "Generated by Resolve".
    static func presetName(forFileName fileName: String) -> String {
        let stem = (fileName as NSString).deletingPathExtension
        let spaced = stem.replacingOccurrences(of: "_", with: " ")
        let squeezed = spaced.split(separator: " ", omittingEmptySubsequences: true).joined(separator: " ")
        return squeezed.isEmpty ? stem : squeezed
    }
}

/// The app-wide store of imported LUTs — the cubes beside `custom_presets.json`
/// in the storage root, one file per distinct content hash, with a small JSON
/// index of what was imported when. A LUT *preset* is a `CustomPreset` whose
/// adjustments carry a `LUTLayer` naming one of these; the store keeps the
/// bytes, the preset keeps the name and the strength.
///
/// Also the Kit's way back from an id to pixels: `installResolver` gives
/// `LUTRegistry` a lookup that reads the store's file, and failing that any
/// project folder's own `luts/` copy — which is how a transferred project
/// renders on a device that never imported the cube.
@MainActor
final class LUTStore: ObservableObject {
    static let shared = LUTStore()

    @Published private(set) var files: [LUTFile] = []
    /// Set when a write failed, for the sheet to say so.
    @Published var lastError: String?

    private let folderURL: URL
    private let indexURL: URL

    init(rootURL: URL? = nil) {
        let root = rootURL ?? StorageRoot.current
        folderURL = Self.folderURL(under: root)
        indexURL = root.appendingPathComponent(Self.indexName)
        load()
        Self.installResolver()
    }

    nonisolated static let folderName = "luts"
    nonisolated static let indexName = "luts.json"

    nonisolated static func folderURL(under root: URL) -> URL {
        root.appendingPathComponent(folderName, isDirectory: true)
    }

    // MARK: - Reading

    func file(id: String) -> LUTFile? { files.first { $0.id == id } }

    /// The parsed cube, through the registry (read once, kept).
    func cube(for id: String) -> CubeLUT? { LUTRegistry.shared.cube(for: id) }

    func fileURL(for id: String) -> URL { folderURL.appendingPathComponent(id + ".cube") }

    // MARK: - Importing

    /// Copies a `.cube` the user picked into the store and parses it. A
    /// cube already present (same bytes) is not duplicated: the existing
    /// record comes back, so two imports of one file make two presets over
    /// one file. Security-scoped: the picker's URL is opened here.
    @discardableResult
    func importCube(from url: URL) throws -> LUTFile {
        let accessed = url.startAccessingSecurityScopedResource()
        defer { if accessed { url.stopAccessingSecurityScopedResource() } }
        let data = try Data(contentsOf: url)
        return try importCube(data: data, fileName: url.lastPathComponent)
    }

    @discardableResult
    func importCube(data: Data, fileName: String) throws -> LUTFile {
        let cube = try CubeLUT.parse(data)
        if let existing = file(id: cube.contentHash) {
            LUTRegistry.shared.register(cube)
            return existing
        }
        try FileManager.default.createDirectory(at: folderURL, withIntermediateDirectories: true)
        try data.write(to: fileURL(for: cube.contentHash), options: .atomic)
        let record = LUTFile(
            id: cube.contentHash, fileName: fileName, title: cube.title, size: cube.size,
            byteCount: data.count, importedAt: Date(), isLikelyLogInput: cube.isLikelyLogInput)
        files.append(record)
        LUTRegistry.shared.register(cube)
        persist()
        return record
    }

    /// Removes the store's file and record. The registry keeps what it has
    /// read until the app quits; projects keep their own copies for good.
    func delete(id: String) {
        files.removeAll { $0.id == id }
        try? FileManager.default.removeItem(at: fileURL(for: id))
        LUTRegistry.shared.forget(id)
        persist()
    }

    // MARK: - Projects

    /// Puts the cube into `folder/luts/` unless it is already there — the
    /// copy a `.lapse` archive and a device transfer carry (`ProjectArchive
    /// .transferableSubfolders`). Silent when the store has no file for the
    /// id: the project may have brought its own, or the id may be a cube
    /// this device never held.
    func ensureCopy(of id: String, inProjectFolder folder: URL) {
        let destinationFolder = Self.folderURL(under: folder)
        let destination = destinationFolder.appendingPathComponent(id + ".cube")
        guard !FileManager.default.fileExists(atPath: destination.path) else { return }
        let source = fileURL(for: id)
        guard FileManager.default.fileExists(atPath: source.path) else { return }
        do {
            try FileManager.default.createDirectory(at: destinationFolder, withIntermediateDirectories: true)
            try FileManager.default.copyItem(at: source, to: destination)
        } catch {
            MediaWorkQueue.note("could not copy LUT \(id.prefix(12)) into \(folder.lastPathComponent): \(error.localizedDescription)", isError: true)
        }
    }

    // MARK: - The registry's lookup

    /// Gives `LUTRegistry` a way from an id to a cube — see `LUTResolver`.
    /// Called from the graders' static initialisers, off the main actor.
    nonisolated static func installResolver() {
        LUTResolver.install()
    }

    // MARK: - Disk

    private func load() {
        guard let data = try? Data(contentsOf: indexURL) else { return }
        do {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            files = try decoder.decode([LUTFile].self, from: data)
        } catch {
            // A corrupt index must not take the sheet down: the files are
            // still there for the registry, and the next import rewrites it.
            files = []
        }
    }

    private func persist() {
        do {
            let encoder = JSONEncoder()
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            encoder.dateEncodingStrategy = .iso8601
            try encoder.encode(files).write(to: indexURL, options: .atomic)
            lastError = nil
        } catch {
            lastError = "Couldn't save your LUTs: \(error.localizedDescription)"
        }
    }
}

/// The registry's lookup, kept outside the main-actor store so a render
/// thread can install and run it. Idempotent. Reads the store's own file
/// first, then every project folder's `luts/` — a transferred project's copy.
enum LUTResolver {
    private static let lock = NSLock()
    private nonisolated(unsafe) static var installed = false

    static func install() {
        lock.lock()
        defer { lock.unlock() }
        guard !installed else { return }
        installed = true
        let root = StorageRoot.current
        let store = LUTStore.folderURL(under: root)
        let projects = root.appendingPathComponent("Projects", isDirectory: true)
        LUTRegistry.shared.setResolver { id in
            guard !id.isEmpty, !id.contains("/"), !id.contains("..") else { return nil }
            let own = store.appendingPathComponent(id + ".cube")
            if let cube = try? CubeLUT.parse(contentsOf: own) { return cube }
            guard let folders = try? FileManager.default.contentsOfDirectory(
                at: projects, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]) else { return nil }
            for folder in folders {
                let candidate = LUTStore.folderURL(under: folder).appendingPathComponent(id + ".cube")
                if FileManager.default.fileExists(atPath: candidate.path),
                   let cube = try? CubeLUT.parse(contentsOf: candidate) {
                    return cube
                }
            }
            return nil
        }
    }
}
