import Foundation
import LetsLapseKit

/// One imported cube, as the store lists it. The pixels live in the file
/// (`luts/<hash>.cube`) and, once read, in `LUTRegistry`; this is what the
/// Presets sheet shows about it.
struct LUTFile: Identifiable, Codable, Equatable {
    /// The cube's content hash — `LUTLayer.id`, and the file's name.
    var id: String
    /// The file name it was imported under, extension included.
    var fileName: String
    /// The file's own `TITLE`, kept as a note ("Generated by Resolve").
    var title: String
    /// Entries per axis.
    var size: Int
    var byteCount: Int
    var importedAt: Date
    /// True when the cube expects a log-encoded picture (`CubeLUT.isLikelyLogInput`).
    var isLikelyLogInput: Bool

    var sizeDescription: String { "\(size) × \(size) × \(size)" }

    /// Who made it, from the title — nil when the title names nobody.
    var maker: String? {
        let lower = title.lowercased()
        if lower.contains("resolve") { return "Resolve" }
        if lower.contains("vegas") { return "VEGAS Pro" }
        if lower.contains("lutcreator") { return "lutCreatorJs" }
        if lower.contains("iwltbap") { return "IWLTBAP" }
        let trimmed = title.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }

    /// "Teal_and_Orange.cube" → "Teal and Orange": the name a preset starts
    /// with. Never the TITLE — five of Steven's eight say "Generated by Resolve".
    static func presetName(forFileName fileName: String) -> String {
        let stem = (fileName as NSString).deletingPathExtension
        let spaced = stem.replacingOccurrences(of: "_", with: " ")
        let squeezed = spaced.split(separator: " ", omittingEmptySubsequences: true).joined(separator: " ")
        return squeezed.isEmpty ? stem : squeezed
    }
}

/// The app-wide store of imported LUTs — the cubes beside `custom_presets.json`
/// in the storage root, one file per distinct content hash, with a small JSON
/// index of what was imported when. A LUT *preset* is a `CustomPreset` whose
/// adjustments carry a `LUTLayer` naming one of these; the store keeps the
/// bytes, the preset keeps the name and the strength.
///
/// A LUT is a library asset identified by its content hash
/// (docs/lut-library-assets.md): the project names it, this store holds it,
/// and the cube is written into a project folder only for an export or a
/// transfer (`AppModel.materialiseLUTs`) and folded back into the receiving
/// library's store on arrival (`AppModel.adoptLUTs`).
///
/// Also the Kit's way back from an id to pixels: `installResolver` gives
/// `LUTRegistry` a lookup that reads the store's file, and failing that a
/// legacy per-project copy from before 2026-09-18, until the fold has
/// moved them all in.
@MainActor
final class LUTStore: ObservableObject {
    /// Replaced between models by a library switch (libraries plan L22);
    /// the new store's init re-points the resolver at the new root.
    static private(set) var shared = LUTStore()
    static func reroot() { shared = LUTStore() }

    @Published private(set) var files: [LUTFile] = []
    /// Set when a write failed, for the sheet to say so.
    @Published var lastError: String?

    private let folderURL: URL
    private let indexURL: URL

    init(rootURL: URL? = nil) {
        let root = rootURL ?? StorageRoot.current
        folderURL = Self.folderURL(under: root)
        indexURL = root.appendingPathComponent(Self.indexName)
        load()
        adoptOrphanFiles()
        LUTResolver.install(root: root)
        LLog("luts: \(files.count) imported LUT(s) at \(folderURL.path)")
    }

    nonisolated static let folderName = "luts"
    nonisolated static let indexName = "luts.json"
    /// The records of the cubes an archive or a transfer carries, beside
    /// them in its `luts/` (docs/lut-library-assets.md §4).
    nonisolated static let archiveIndexName = "index.json"

    nonisolated static func folderURL(under root: URL) -> URL {
        root.appendingPathComponent(folderName, isDirectory: true)
    }

    // MARK: - Reading

    func file(id: String) -> LUTFile? { files.first { $0.id == id } }

    /// The parsed cube, through the registry (read once, kept).
    func cube(for id: String) -> CubeLUT? { LUTRegistry.shared.cube(for: id) }

    func fileURL(for id: String) -> URL { folderURL.appendingPathComponent(id + ".cube") }

    // MARK: - Importing

    /// Copies a `.cube` the user picked into the store and parses it. A
    /// cube already present (same bytes) is not duplicated: the existing
    /// record comes back, so two imports of one file make two presets over
    /// one file. Security-scoped: the picker's URL is opened here.
    @discardableResult
    func importCube(from url: URL) throws -> LUTFile {
        let accessed = url.startAccessingSecurityScopedResource()
        defer { if accessed { url.stopAccessingSecurityScopedResource() } }
        let data = try Data(contentsOf: url)
        return try importCube(data: data, fileName: url.lastPathComponent)
    }

    @discardableResult
    func importCube(data: Data, fileName: String) throws -> LUTFile {
        let cube = try CubeLUT.parse(data)
        if let existing = file(id: cube.contentHash) {
            LUTRegistry.shared.register(cube)
            return existing
        }
        try FileManager.default.createDirectory(at: folderURL, withIntermediateDirectories: true)
        try data.write(to: fileURL(for: cube.contentHash), options: .atomic)
        let record = LUTFile(
            id: cube.contentHash, fileName: fileName, title: cube.title, size: cube.size,
            byteCount: data.count, importedAt: Date(), isLikelyLogInput: cube.isLikelyLogInput)
        files.append(record)
        LUTRegistry.shared.register(cube)
        persist()
        return record
    }

    /// Removes the store's file and record. The registry keeps what it has
    /// read until the app quits. The caller guards this with the index's
    /// reference count (`ManagePresetsView.delete`): the store is the one
    /// place the cube a project names lives.
    func delete(id: String) {
        files.removeAll { $0.id == id }
        try? FileManager.default.removeItem(at: fileURL(for: id))
        LUTRegistry.shared.forget(id)
        persist()
    }

    // MARK: - The registry's lookup

    /// Gives `LUTRegistry` a way from an id to a cube — see `LUTResolver`.
    /// Called from the graders' static initialisers, off the main actor.
    nonisolated static func installResolver() {
        LUTResolver.install()
    }

    // MARK: - Disk

    private func load() {
        guard let data = try? Data(contentsOf: indexURL) else { return }
        do {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            files = try decoder.decode([LUTFile].self, from: data)
        } catch {
            // A corrupt index must not take the sheet down: the files are
            // still there for the registry, and the next import rewrites it.
            files = []
        }
    }

    /// Cube files in the folder with no record — a fold that moved the
    /// project copies in, a hand-copied library, a record lost to a corrupt
    /// index — get one, parsed from the file, so the sheet lists them and a
    /// delete can find them. A file not named by its content hash is left
    /// alone and logged: a grade names the hash, and a misnamed file cannot
    /// answer for it.
    private func adoptOrphanFiles() {
        guard let names = try? FileManager.default.contentsOfDirectory(atPath: folderURL.path) else { return }
        var adopted = 0
        for name in names.sorted() where name.hasSuffix(".cube") {
            let stem = String(name.dropLast(".cube".count))
            guard file(id: stem) == nil else { continue }
            let url = folderURL.appendingPathComponent(name)
            guard let data = try? Data(contentsOf: url), let cube = try? CubeLUT.parse(data) else {
                LLog("luts: \(name) does not parse — left alone")
                continue
            }
            guard cube.contentHash == stem else {
                LLog("luts: \(name) is not named by its content hash (\(cube.contentHash.prefix(12))) — left alone")
                continue
            }
            let made = (try? url.resourceValues(forKeys: [.creationDateKey]))?.creationDate ?? Date()
            files.append(LUTFile(
                id: stem, fileName: name, title: cube.title, size: cube.size, byteCount: data.count,
                importedAt: made, isLikelyLogInput: cube.isLikelyLogInput))
            LUTRegistry.shared.register(cube)
            adopted += 1
        }
        if adopted > 0 {
            persist()
            LLog("luts: adopted \(adopted) cube file(s) that had no record")
        }
    }

    private func persist() {
        do {
            let encoder = JSONEncoder()
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            encoder.dateEncodingStrategy = .iso8601
            try encoder.encode(files).write(to: indexURL, options: .atomic)
            lastError = nil
        } catch {
            lastError = "Couldn't save your LUTs: \(error.localizedDescription)"
        }
    }
}

/// The registry's lookup, kept outside the main-actor store so a render
/// thread can install and run it. Installed once; the root it reads is the
/// one the last `LUTStore.init` gave it, so a library switch on the phone
/// re-points it (until 2026-09-18 it latched the first root for good).
/// Reads the store's own file first, then a legacy per-project copy from
/// before the fold — never a folder walk per frame: the registry remembers
/// a miss until the store changes.
enum LUTResolver {
    private static let lock = NSLock()
    private nonisolated(unsafe) static var installed = false
    private nonisolated(unsafe) static var root: URL?

    /// With a root: point the lookup there (a change forgets the cached
    /// misses). Without one — the graders' static initialisers, which may
    /// run before any store exists — the process's storage root.
    static func install(root newRoot: URL? = nil) {
        lock.lock()
        defer { lock.unlock() }
        let resolved = newRoot ?? root ?? StorageRoot.current
        let changed = root != nil && root != resolved
        root = resolved
        if installed {
            if changed { LUTRegistry.shared.forgetMisses() }
            return
        }
        installed = true
        LUTRegistry.shared.setResolver { id in resolve(id) }
    }

    private static func currentRoot() -> URL? {
        lock.lock()
        defer { lock.unlock() }
        return root
    }

    private static func resolve(_ id: String) -> CubeLUT? {
        guard !id.isEmpty, !id.contains("/"), !id.contains(".."), let root = currentRoot() else { return nil }
        let own = LUTStore.folderURL(under: root).appendingPathComponent(id + ".cube")
        if let cube = try? CubeLUT.parse(contentsOf: own) { return cube }
        // A legacy copy inside a project folder (before 2026-09-18), read
        // where it is; the fold moves these into the store.
        let projects = root.appendingPathComponent("Projects", isDirectory: true)
        guard let folders = try? FileManager.default.contentsOfDirectory(
            at: projects, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]) else { return nil }
        for folder in folders {
            let candidate = LUTStore.folderURL(under: folder).appendingPathComponent(id + ".cube")
            if FileManager.default.fileExists(atPath: candidate.path),
               let cube = try? CubeLUT.parse(contentsOf: candidate) {
                LLog("luts: \(id.prefix(12)) read from a legacy copy in \(folder.lastPathComponent) — run tools/fold_luts.py")
                return cube
            }
        }
        return nil
    }
}
